name: sar
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - jupyter
  - ipykernel
  - ipywidgets
  - notebook
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - statsmodels
  - altair
  - pyarrow
  - openpyxl
  - requests
  - beautifulsoup4
  - nltk
  - gensim
  - spacy
  - transformers
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8  # Optional, if GPU available
  - jupyterlab
  - streamlit
  - plotly
  - pyyaml
  - sqlalchemy
  - pip:
      - umap-learn
      - wordcloud
      - python-dotenv
      - openai
      - playwright
      - selenium
      - webdriver-manager
      - httpx
      - rich
      - langcodes
      - cloudpathlib
